spring:
  application:
    name: Flash-Food

  datasource:
    hikari:
      driver-class-name: ${driverClassName}
      username: ${userName}
      password: ${password}
      jdbc-url: ${jdbcUrl}
      connection-timeout: ${connectionTimeOut}
      idle-timeout: ${idleTimeOut}
      max-lifetime: ${maxLifeTime}
      minimum-idle: ${minimumIdle}
      maximum-pool-size: ${maximumPoolSize}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${hibernateDialect}
        ejb:
          use_class_enhancer: true
    show-sql: true

server:
  servlet:
    context-path: /flash-food
  port: 8080

jwt:
  secret: ${secret}